@startuml
title 内盗审核流程

(*) --> "员工打卡信息生单入库"

partition 供应商初审 {
  "员工打卡信息生单入库" -r-> "系统派发给供应商审核"
  "系统派发给供应商审核" --> "选定打卡/离店监控照片"
  "选定打卡/离店监控照片" --> "选择离店时员工手持物品情况"
  "选择离店时员工手持物品情况" --> "监控回溯判定盗损"
  "监控回溯判定盗损" --> "有盗损" as a1
  a1 --> "填写盗损信息" as d1
  "监控回溯判定盗损" --> "无盗损" as b1
  b1 --> "备注审核信息" as e1
  "监控回溯判定盗损" --> "无法确定" as c1
  c1 --> e1
  d1 --> ==S1==
  e1 --> ==S1==
  ==S1== --> "提交审核结果" as f1
}

partition 总部复审 {
  f1 -r-> "有盗损或无法判断的case落入复审池"
  "有盗损或无法判断的case落入复审池" --> "查看初审定位监控"
  if "判定初审质量" then
  -r-> [正确]"判定盗损" as judgeSteal
  else
  -l-> [错误]"备注判定原因"
  endif
  judgeSteal --> "有盗损" as a2
  a2 --> "填写盗损信息" as d2
  judgeSteal --> "无盗损" as b2
  b2 --> "备注审核信息" as e2
  judgeSteal --> "无法确定" as c2
  c2 --> e2
  d2 --> ==S2==
  e2 --> ==S2==
  "备注判定原因" --> ==S2==
  ==S2== --> "提交审核结果" as f2
}

partition 内控终审 {
  f2 -r-> "结合监控与初、复审结果给出盗损判定" as judgeSteal2
  judgeSteal2 --> "有盗损" as a3
  judgeSteal2 --> "无盗损" as b3
  judgeSteal2 --> "无法确定" as c3
  a3 --> ==S3==
  b3 --> ==S3==
  c3 --> ==S3==
  ==S3== --> "情况说明，提交审核结果"
}

-r-> (*)

@enduml
