@startuml
title 看板分享流程

(*) --> "看板负责人 / 平台管理员 登录"
partition 数据中心 {
  "看板负责人 / 平台管理员 登录" --> "进入看板管理"
  "进入看板管理" --> "选择需要分享的看板，点击分享"
  "选择需要分享的看板，点击分享" --> "输入需要使用该看板系统的域名"
  "输入需要使用该看板系统的域名" --> "校验通过，获得iframe标签"
  "校验该系统权限" -r-> "返回看板数据"
}

partition 三方系统 {
  "校验通过，获得iframe标签" -d-> "粘贴至前端项目中，自行定义样式"
  "粘贴至前端项目中，自行定义样式" --> "三方系统权限校验"
  "三方系统权限校验" --> "加载看板"
  "加载看板" --> "校验该系统权限"
}

"返回看板数据" -r-> (*)
@enduml
