@startuml
title 标签至人群建立

partition 数据中心 {
  partition 标签管理 {
    (*) -r-> "用户在某个主题下建立标签，通过sql抽取需要的值"
    -r-> "保存标签配置"
    -r-> "启用标签"
  }
  partition 人群管理 {
    "启用标签" -d-> "使用已启用标签配置人群规则"
    --> "选择关联标签(业务关注的值)"
    --> "启用人群"
    --> "执行人群提取任务"
  }
}

partition 调度系统 {
  "执行人群提取任务" -d-> "创建对应job"
  "创建对应job" --> "对应时间段触发任务"
  "对应时间段触发任务" --> "执行规则标签sql，过滤人群信息"
  "执行规则标签sql，过滤人群信息" --> "从过滤出的信息中抽取关联标签值"
}

partition 集群服务 {
  "从过滤出的信息中抽取关联标签值" -u-> "写入人群数据表"
  "写入人群数据表" --> (*)
}

@enduml
