@startuml pageInter
title 普通用户配置接入
actor       用户           as User
participant 前端页面        as Fe
participant 后端接口        as Be
participant 数据中心数据库  as Db
participant 调度系统       as Jenkins
participant 蜂利器         as Bsharp
participant 负责人         as Owner
participant 集群服务       as HiveServer

== 填写库-表配置 ==

loop N次（N = 生成目标表数量）
  group 单表接入

    User -> Fe: 选择DB(Suggest)
    Fe -> User: 提供Suggest，根据db_code查询数据表
    User -> Fe: 选择数据表
    User -> Fe: 选择是否接入业务数据库，若是则选择业务数据库名称

  end

  group 单库分表接入

    User -> Fe: 选择DB(Suggest)，并添加分表
    loop M次（M = 分表数量）
      User -> Fe: 填写匹配数据表正则表达式
      Fe -> User: 校验该接入中是否存在相同表达式
    end
    User -> Fe: 选择是否接入业务数据库，若是则选择业务数据库名称

  end

  group 分库分表接入

    loop M次（M = 库-表数量）
      User -> Fe: 选择DB(Suggest)
      User -> Fe: 填写匹配数据表正则表达式
      Fe -> User: 校验该接入中是否存在相同库-表
    end
    User -> Fe: 选择是否接入业务数据库，若是则选择业务数据库名称

  end

end
Fe --> User: 校验必填项

== 其余配置 ==

User -> Fe: 填写申请名称、调度相关配置、描述
Fe -> User: 校验必填项

== 保存 ==

User --> Fe: 点击保存/新建
Fe --> Fe: 校验必填项与是否存在完全相同的接入
Fe --> Be: 请求接口保存
Be --> Db: 将接入配置 insert / update 表
Db --> Be: success
Be --> Fe: status: 0
Fe --> User: 提示保存成功

== 发布 ==

User --> Fe: 点击发布
Fe --> Be: 携带id请求发布
Be --> Bsharp: 申请创建流程
Bsharp --> Owner: 推送至负责人
alt 同意 
  Owner --> Bsharp: 负责人处理
  Bsharp --> Be: 回调接口
  Be --> Db: 更新接入状态：已完成
  Be --> Jenkins: 创建接入任务 
  Jenkins --> HiveServer: 定时触发接入
else 拒绝
  Owner --> Bsharp: 负责人拒绝
  Bsharp --> Be: 回调接口
  Be --> Db: 更新接入状态：已拒绝
end


@enduml
