@startuml
title 开发新建接入

partition 数据中心 {

  (*) --> "用户填写接入信息"
  --> "保存配置"
  --> "按照用户配置生成jenkins任务"

}

partition 调度系统 {

  "按照用户配置生成jenkins任务" --> "对应时间段触发任务"
  "对应时间段触发任务" --> "调用save接口接入至hive"

}

--> (*)

@enduml
