@startuml
title 普通用户新建接入

partition 数据中心 {
  (*) -r-> "用户填写接入信息"
  -r-> "保存配置"
  -r-> "点击申请发布"
  -r-> "更新状态审核中"

  "回调更新状态已完成" --> "按照用户配置生成jenkins任务"
  "回调更新状态已拒绝" --> ==DONE==

}

partition 蜂利器审批 {
  "更新状态审核中" -r-> "建立审批流"
  -->"负责人收到流程信息"
  if "负责人同意" then
    -->[true] "回调更新状态已完成"
  else 
    -->[false] "回调更新状态已拒绝"
}

partition 调度系统 {
  "按照用户配置生成jenkins任务" -d-> "对应时间段触发任务"
  "对应时间段触发任务" -r-> "调用save接口接入至hive"
  "调用save接口接入至hive" --> ==DONE==
}

==DONE== --> (*)

@enduml
