@startuml
title 地理信息可视化

(*) --> 关联不同业务主体

partition 配置模块 {
  关联不同业务主体 --> 提供地图业务的配置与数据上传入口
}

partition 地图服务 {
  partition 业务模块 {
    提供地图业务的配置与数据上传入口 --> "提供当前主体下已配置的业务, 修改触发配置与地图数据更新"
  }

  partition 筛选器模块 {
    "提供当前主体下已配置的业务, 修改触发配置与地图数据更新" --> "依据配置提供筛选（接口）"
  }

  partition 数据统计模块 {
    "依据配置提供筛选（接口）" --> "依据配置展示地图数据统计（可能存在与地图的联动, 后续还会有导出需求）"
  }

  partition 地图模块 {
    "依据配置提供筛选（接口）" --> "根据业务配置的展示类型与上传的数据提供不同的能力"
  }
}

"依据配置展示地图数据统计（可能存在与地图的联动, 后续还会有导出需求）" --> ==END==
"根据业务配置的展示类型与上传的数据提供不同的能力" --> ==END==


--> (*)

@enduml
